spring:
  data:
    redis:
      host: redis-1-service
  datasource:
    url: jdbc:mariadb://mariadb-1-service:3306/hogamapp__prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: create
logging:
  level:
    root: info
    com.ll.demo4.app: info
    org.hibernate.type.descriptor.sql: info
custom:
  genFileDirPath: /gen
  site:
    baseUrl: "https://hogam.app"