server:
  shutdown: graceful
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
    include:
      - security
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope: profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8010/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: info
    com.ll.hogamapp: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  genFile:
    dirName: gen
    dirParentPath: c:/temp/hogamapp
  site:
    name: 호감앱
    baseUrl: "http://localhost:8010"